version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker build
          command: ./build.sh
